Removed WindowsSettingBehavior due to crash
Exception: System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at void System.Windows.Threading.Dispatcher.VerifyAccess()+ThrowVerifyAccess()
   at T Microsoft.Xaml.Behaviors.Behavior<T>.get_AssociatedObject()
   at void MahApps.Metro.Behaviors.WindowsSettingBehavior.SaveWindowState() in C:/projects/mahapps-metro/src/MahApps.Metro/Behaviors/WindowsSettingBehavior.cs:line 151